apiVersion: apps/v1
kind: Deployment
metadata:
  name: mzhtml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mzhtml
  template:
    metadata:
      labels:
        app: mzhtml
    spec:
      containers:
      - name: mzhtml
        image: mzti/mzhtml
        ports:
        - containerPort: 80